import type { AllianceFields } from "./alliance.js";
import type { AlliancePositionFields } from "./alliancePosition.js";
import type { AwardFields } from "./award.js";
import type { BankTaxrecFields } from "./bankTaxRec.js";
import type { BountyFields } from "./bounty.js";
import type { BulletinFields } from "./bullentin.js";
import type { BulletinReplyFields } from "./bullentinReplies.js";
import type { CityFields } from "./cities.js";
import type { TradeFields } from "./trade.js";
import type { TreasureFields } from "./treasure.js";
import type { WarFields } from "./war.js";

export interface NationFields {
  id?: string;
  alliance_id?: number;
  alliance_position?: string;
  alliance_position_id?: number;
  nation_name?: string;
  leader_name?: string;
  continent?: string;
  war_policy?: string;
  war_policy_turns?: number;
  domestic_policy?: string;
  domestic_policy_turns?: number;
  color?: string;
  num_cities?: number;
  score?: number;
  update_tz?: number;
  population?: number;
  flag?: string;
  vacation_mode_turns?: number;
  beige_turns?: number;
  espionage_available?: boolean;
  last_active?: string;
  date?: string;
  soldiers?: number;
  tanks?: number;
  aircraft?: number;
  ships?: number;
  missiles?: number;
  nukes?: number;
  spies?: number;
  soldiers_today?: number;
  tanks_today?: number;
  aircraft_today?: number;
  ships_today?: number;
  missiles_today?: number;
  nukes_today?: number;
  spies_today?: number;
  discord?: string;
  discord_id?: string;
  turns_since_last_city?: number;
  turns_since_last_project?: number;
  money?: number;
  coal?: number;
  oil?: number;
  uranium?: number;
  iron?: number;
  bauxite?: number;
  lead?: number;
  gasoline?: number;
  munitions?: number;
  steel?: number;
  aluminum?: number;
  food?: number;
  credits?: number;
  projects?: number;
  project_bits?: string;
  iron_works?: boolean;
  bauxite_works?: boolean;
  arms_stockpile?: boolean;
  emergency_gasoline_reserve?: boolean;
  mass_irrigation?: boolean;
  international_trade_center?: boolean;
  missile_launch_pad?: boolean;
  nuclear_research_facility?: boolean;
  iron_dome?: boolean;
  vital_defense_system?: boolean;
  central_intelligence_agency?: boolean;
  center_for_civil_engineering?: boolean;
  propaganda_bureau?: boolean;
  uranium_enrichment_program?: boolean;
  urban_planning?: boolean;
  advanced_urban_planning?: boolean;
  space_program?: boolean;
  spy_satellite?: boolean;
  moon_landing?: boolean;
  pirate_economy?: boolean;
  recycling_initiative?: boolean;
  telecommunications_satellite?: boolean;
  green_technologies?: boolean;
  arable_land_agency?: boolean;
  clinical_research_center?: boolean;
  specialized_police_training_program?: boolean;
  advanced_engineering_corps?: boolean;
  government_support_agency?: boolean;
  research_and_development_center?: boolean;
  metropolitan_planning?: boolean;
  military_salvage?: boolean;
  fallout_shelter?: boolean;
  activity_center?: boolean;
  bureau_of_domestic_affairs?: boolean;
  advanced_pirate_economy?: boolean;
  mars_landing?: boolean;
  surveillance_network?: boolean;
  guiding_satellite?: boolean;
  nuclear_launch_facility?: boolean;
  military_research_center?: boolean;
  military_doctrine?: boolean;
  moon_landing_date?: string;
  mars_landing_date?: string;
  wars_won?: number;
  wars_lost?: number;
  tax_id?: number;
  alliance_seniority?: number;
  gross_national_income?: number;
  gross_domestic_product?: number;
  soldier_casualties?: number;
  soldier_kills?: number;
  tank_casualties?: number;
  tank_kills?: number;
  aircraft_casualties?: number;
  aircraft_kills?: number;
  ship_casualties?: number;
  ship_kills?: number;
  missile_casualties?: number;
  missile_kills?: number;
  nuke_casualties?: number;
  nuke_kills?: number;
  spy_casualties?: number;
  spy_kills?: number;
  spy_attacks?: number;
  money_looted?: number;
  total_infrastructure_destroyed?: number;
  total_infrastructure_lost?: number;
  vip?: boolean;
  commendations?: number;
  denouncements?: number;
  offensive_wars_count?: number;
  defensive_wars_count?: number;
  economic_policy?: string;
  social_policy?: string;
  government_type?: string;
  credits_redeemed_this_month?: number;
  alliance_join_date?: string;
  cities_discount?: number;
}

export interface NationQueryParams {
  id?: number[];
  min_id?: number[];
  max_id?: number[];
  nation_name?: string[];
  leader_name?: string[];
  alliance_id?: number[];
  alliance_position?: number[];
  alliance_position_id?: number[];
  color?: string[];
  created_before?: string;
  created_after?: string;
  active_since?: string;
  active_before?: string;
  min_score?: number;
  max_score?: number;
  cities?: number[];
  min_cities?: number;
  max_cities?: number;
  vmode?: boolean;
  discord?: string[];
  discord_id?: string[];
  tax_id?: number[];
  //continent?: Continents[];
  //orderBy?: QueryNationsOrderByOrderByClause[];
}

export interface NationRelations {
    alliance: AllianceFields;
    alliance_position_info: AlliancePositionFields;
    awards: AwardFields;
    bankrecs: BankTaxrecFields;
    bounties: BountyFields;
    bulletins: BulletinFields;
    bulletin_replies: BulletinReplyFields;
    cities: CityFields;
    trades: TradeFields;
    taxrecs: BankTaxrecFields;
    treasures: TreasureFields;
    wars: WarFields;
}