import type { AllianceFields } from "./alliance.js";
import type { NationFields } from "./nation.js";

export interface WarFields {
    id: string;
    date: string;
    reason: string;
    war_type: string;
    ground_control: number;
    air_superiority: number;
    naval_blockade: number;
    winner_id: number;
    turns_left: number;
    att_id: number;
    att_alliance_id: number;
    att_alliance_position: string;
    def_id: number;
    def_alliance_id: number;
    def_alliance_position: string;
    att_points: number;
    def_points: number;
    att_peace: boolean;
    def_peace: boolean;
    att_resistance: number;
    def_resistance: number;
    att_fortify: boolean;
    def_fortify: boolean;
    att_gas_used: number;
    def_gas_used: number;
    att_mun_used: number;
    def_mun_used: number;
    att_alum_used: number;
    def_alum_used: number;
    att_steel_used: number;
    def_steel_used: number;
    att_infra_destroyed: number;
    def_infra_destroyed: number;
    att_money_looted: number;
    def_money_looted: number;
    att_soldiers_killed: number;
    def_soldiers_killed: number;
    att_tanks_killed: number;
    def_tanks_killed: number;
    att_aircraft_killed: number;
    def_aircraft_killed: number;
    att_ships_killed: number;
    def_ships_killed: number;
    att_missiles_used: number;
    def_missiles_used: number;
    att_nukes_used: number;
    def_nukes_used: number;
    att_infra_destroyed_value: number;
    def_infra_destroyed_value: number;
}