export interface Nation {
    id: number,
    alliance_id: number,
    alliance_position: string,
    alliance_position_id: number,
    nation_name: string,
    leader_name: string,
    continent: string,
    war_policy: string,
    domestic_policy: string,
    war_policy_turns: number,
    domestic_policy_turns: number,
    color: string,
    num_cities: number,
    score: number,
    update_tz: string | null,
    population: number,
    flag: string,
    vacation_mode_turns: number,
    beige_turns: number,
    espionage_available: boolean,
    date: string,
    soldiers: number,
    tanks: number,
    aircraft: number,
    ships: number,
    missiles: number,
    nukes: number,
    spies: number,
    discord: string,
    turns_since_last_city: number,
    turns_since_last_project: number,
    money: number | null,
    coal: number | null,
    oil: number | null,
    uranium: number | null,
    iron: number | null,
    bauxite: number | null,
    lead: number | null,
    gasoline: number | null,
    munitions: number | null,
    steel: number | null,
    aluminum: number | null,
    food: number | null,
    projects: number,
    iron_works: number,
    bauxite_works: number,
    arms_stockpile: number,
    emergency_gasoline_reserve: number,
    mass_irrigation: number,
    international_trade_center: number,
    missile_launch_pad: number,
    nuclear_research_facility: number,
    iron_dome: number,
    vital_defense_system: number,
    central_intelligence_agency: number,
    center_for_civil_engineering: number,
    propaganda_bureau: number,
    uranium_enrichment_program: number,
    urban_planning: number,
    advanced_urban_planning: number,
    space_program: number,
    spy_satellite: number,
    moon_landing: number,
    moon_landing_date: string | null,
    pirate_economy: number,
    recycling_initiative: number,
    telecommunications_satellite: number,
    green_technologies: number,
    arable_land_agency: number,
    clinical_research_center: number,
    specialized_police_training_program: number,
    advanced_engineering_corps: number,
    government_support_agency: number,
    research_and_development_center: number,
    resource_production_center: number,
    wars_won: number,
    wars_lost: number,
    tax_id: number,
    alliance_seniority: number,
    gross_national_income: number,
    gross_domestic_product: number,
    soldier_casualties: number,
    soldier_kills: number,
    tank_casualties: number,
    tank_kills: number,
    aircraft_casualties: number,
    aircraft_kills: number,
    ship_casualties: number,
    ship_kills: number,
    missile_casualties: number,
    missile_kills: number,
    nuke_casualties: number,
    nuke_kills: number,
    spy_casualties: number | null,
    spy_kills: number | null,
    money_looted: number,
    metropolitan_planning: number,
    military_salvage: number,
    fallout_shelter: number,
    bureau_of_domestic_affairs: number,
    advanced_pirate_economy: number,
    mars_landing: number,
    mars_landing_date: string | null,
    surveillance_network: number,
    guiding_satellite: number,
    nuclear_launch_facility: number,
    project_bits: string
}