/**
 * Project bit positions using standard right-to-left bit indexing.
 * These values represent bit positions where position 0 is the rightmost/least significant bit.
 * Use with standard bit shift operations: (value & (1 << position)) to check if a project is built.
 */
export const ProjectBits = {
    IRON_WORKS: 0,
    BAUXITE_WORKS: 1,
    ARMS_STOCKPILE: 2,
    EMERGENCY_GASOLINE_RESERVE: 3,
    MASS_IRRIGATION: 4,
    INTERNATIONAL_TRADE_CENTRE: 5,
    MISSILE_LAUNCH_PAD: 6,
    NUCLEAR_RESEARCH_FACILITY: 7,
    IRON_DOME: 8,
    VITAL_DEFENCE_SYSTEM: 9,
    INTELLIGENCE_AGENCY: 10,
    CENTER_CIVIL_ENGINEERING: 11,
    PROPAGANDA_BUREAU: 12,
    URANIUM_ENRICHMENT_PROGRAM: 13,
    SPACE_PROGRAM: 16,
    SPY_SATELLITE: 17,
    MOON_LANDING: 18,
    PIRATE_ECONOMY: 19,
    RECYCLING_INITIATIVE: 20,
    TELECOMMUNICATIONS_SATELLITE: 21,
    GREEN_TECHNOLOGIES: 22,
    ARABLE_LAND_AGENCY: 23,
    CLINICAL_RESEARCH_CENTER: 24,
    SPECIALISED_POLICE_TRAINING_PROGRAM: 25,
    ADVANCED_ENGINEERING_CORPS: 26,
    GOVERNMENT_SUPPORT_AGENCY: 27,
    RESEARCH_DEVELOPMENT_CENTER: 28,
    RESOURCE_PRODUCTION_CENTER: 29,
    METROPOLITAN_PLANNING: 30,
    MILITARY_SALVAGE: 31,
    FALLOUT_SHELTER: 32,
    BUREAU_OF_DOMESTIC_AFFAIRS: 33,
    ADV_PIRATE_ECONOMY: 34,
    MARS_LANDING: 35,
    SURVEILLANCE_NETWORK: 36,
    GUIDING_SATELLITE: 37,
    NUCLEAR_LAUNCH_FACILITY: 38,
    MILITARY_RESEARCH_CENTER: 39,
    MILITARY_DOCTORINE: 40,
} as const;

export type ProjectBits = number;